{{- /* Headless service required for StatefulSet DNS resolution */}}
{{- $useStatefulSet := and (eq .Values.storage.mode "sqlite") .Values.storage.persistence.enabled (not .Values.storage.persistence.existingClaim) }}
{{- if $useStatefulSet }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bifrost.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "bifrost.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.bifrost.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.bifrost.cluster.enabled }}
    - port: {{ .Values.bifrost.cluster.gossip.port }}
      targetPort: gossip
      protocol: TCP
      name: gossip
    - port: {{ .Values.bifrost.cluster.gossip.port }}
      targetPort: gossip-udp
      protocol: UDP
      name: gossip-udp
    {{- end }}
{{- end }}
