# Logging API schemas

LogEntry:
  type: object
  description: Log entry
  properties:
    id:
      type: string
    parent_request_id:
      type: string
    provider:
      type: string
    model:
      type: string
    status:
      type: string
      enum: ["processing", "success", "error"]
    object:
      type: string
    timestamp:
      type: string
      format: date-time
    number_of_retries:
      type: integer
    fallback_index:
      type: integer
    latency:
      type: number
    cost:
      type: number
    selected_key_id:
      type: string
    selected_key_name:
      type: string
    virtual_key_id:
      type: string
    virtual_key_name:
      type: string
      nullable: true
    stream:
      type: boolean
    raw_request:
      type: string
    raw_response:
      type: string
    created_at:
      type: string
      format: date-time
    token_usage:
      $ref: '../../schemas/inference/usage.yaml#/BifrostLLMUsage'
    error_details:
      $ref: '../../schemas/inference/common.yaml#/BifrostError'
    input_history:
      type: array
      items:
        $ref: '../../schemas/inference/chat.yaml#/ChatMessage'
    responses_input_history:
      type: array
      items:
        $ref: '../../schemas/inference/responses.yaml#/ResponsesMessage'
    output_message:
      $ref: '../../schemas/inference/chat.yaml#/ChatMessage'
    responses_output:
      type: array
      items:
        $ref: '../../schemas/inference/responses.yaml#/ResponsesMessage'
    embedding_output:
      type: array
      items:
        type: array
        items:
          type: number
    params:
      type: object
      additionalProperties: true
    tools:
      type: array
      items:
        $ref: '../../schemas/inference/chat.yaml#/ChatTool'
    tool_calls:
      type: array
      items:
        $ref: '../../schemas/inference/chat.yaml#/ChatAssistantMessageToolCall'
    speech_input:
      type: object
      additionalProperties: true
    transcription_input:
      type: object
      additionalProperties: true
    image_generation_input:
      type: object
      additionalProperties: true
    speech_output:
      type: object
      additionalProperties: true
    transcription_output:
      type: object
      additionalProperties: true
    image_generation_output:
      type: object
      additionalProperties: true
    cache_debug:
      type: object
      additionalProperties: true
    selected_key:
      type: object
      additionalProperties: true
    virtual_key:
      type: object
      additionalProperties: true

SearchFilters:
  type: object
  description: Log search filters
  properties:
    providers:
      type: array
      items:
        type: string
    models:
      type: array
      items:
        type: string
    status:
      type: array
      items:
        type: string
    objects:
      type: array
      items:
        type: string
    selected_key_ids:
      type: array
      items:
        type: string
    virtual_key_ids:
      type: array
      items:
        type: string
    start_time:
      type: string
      format: date-time
    end_time:
      type: string
      format: date-time
    min_latency:
      type: number
    max_latency:
      type: number
    min_tokens:
      type: integer
    max_tokens:
      type: integer
    min_cost:
      type: number
    max_cost:
      type: number
    missing_cost_only:
      type: boolean
    content_search:
      type: string

SearchLogsResponse:
  type: object
  description: Search logs response
  properties:
    logs:
      type: array
      items:
        $ref: '#/LogEntry'
    total:
      type: integer
    offset:
      type: integer
    limit:
      type: integer

LogStats:
  type: object
  description: Log statistics
  properties:
    total_requests:
      type: integer
    total_tokens:
      type: integer
    total_cost:
      type: number
    average_latency:
      type: number
    success_rate:
      type: number

DroppedRequestsResponse:
  type: object
  description: Dropped requests response
  properties:
    dropped_requests:
      type: integer
      format: int64

FilterDataResponse:
  type: object
  description: Available filter data response
  properties:
    models:
      type: array
      items:
        type: string
    selected_keys:
      type: array
      items:
        $ref: '../../schemas/management/providers.yaml#/Key'
    virtual_keys:
      type: array
      items:
        $ref: '../../schemas/management/governance.yaml#/VirtualKey'

DeleteLogsRequest:
  type: object
  description: Delete logs request
  required:
    - ids
  properties:
    ids:
      type: array
      items:
        type: string

RecalculateCostRequest:
  type: object
  description: Recalculate cost request
  properties:
    filters:
      $ref: '#/SearchFilters'
    limit:
      type: integer
      description: Maximum number of logs to process (default 200, max 1000)

RecalculateCostResponse:
  type: object
  description: Recalculate cost response
  properties:
    total_matched:
      type: integer
    updated:
      type: integer
    skipped:
      type: integer
    remaining:
      type: integer
